<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyBanHang" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-L8JMH5Q\SQLEXPRESS;Initial Catalog=QuanLyBanHang;Integrated Security=True" SettingsObjectName="QuanLyBanHang.Properties.Settings" SettingsPropertyName="QuanLyBanHangConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblHangHoa" Member="tblHangHoas">
    <Type Name="tblHangHoa">
      <Column Name="IDHangHoa" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenHang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoLuongCon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>