//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChiTietHoaDon
    {
        public int IDHoaDon { get; set; }
        public int IDHangHoa { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> DonGia { get; set; }
    
        public virtual tblHangHoa tblHangHoa { get; set; }
        public virtual tblHoaDon tblHoaDon { get; set; }
    }
}
