//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHoaDon
    {
        public int IDHoaDon { get; set; }
        public Nullable<int> IDKhachHang { get; set; }
        public Nullable<int> IDNhanVien { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<int> IDHangHoa { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> DonGia { get; set; }
    
        public virtual tblHangHoa tblHangHoa { get; set; }
        public virtual tblKhachHang tblKhachHang { get; set; }
        public virtual tblNhanVien tblNhanVien { get; set; }
    }
}
